name: flutter_tdd_todos
description: TDDでTODOリストを作ってみる

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_riverpod: ^0.11.0
  sqflite: ^1.3.1+1
  shared_preferences: ^0.5.12
  freezed_annotation:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
dependency_overrides:
  analyzer: '0.39.14'
flutter:

  uses-material-design: true